package icpmapp.entities;

public enum SessionType {
    KEYNOTE,
    FOOD,
    COFFEE,
    PRACTICAL,
    QnA,
    DOCTORALCONSORTIUM,
    PANEL,
    TUTORIAL,
    WORKSHOP,
    DEMO,
    MAIN,
    BPMFORUM,
    EDUCATORSFORUM,
    PROCESSTECHNOLOGYFORUM,
    INDUSTRYFORUM,
    RESPONSIBLEBPMFORUM,
    JOURNALFIRST,
}
