services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_AUTH: yes
      SPRING_MAIL_USERNAME: noreply.ICPM24@gmail.com
      SPRING_MAIL_PASSWORD: smcypgmeryupfovx
      FILE_UPLOAD_DIR: /app/uploads
    volumes:
      - ./uploads:/app/uploads
volumes:
  db_data:
