version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring_security
      SPRING_DATASOURCE_USERNAME: conference
      SPRING_DATASOURCE_PASSWORD: 123qwe
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_AUTH: yes
      SPRING_MAIL_USERNAME: noreply.ICPM24@gmail.com
      SPRING_MAIL_PASSWORD: smcypgmeryupfovx
      FILE_UPLOAD_DIR: /app/uploads
    volumes:
      - ./uploads:/app/uploads

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: spring_security
      MYSQL_USER: conference
      MYSQL_PASSWORD: 123qwe
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: